review_version: 5.0

bookname: review-biblatex-sample
booktitle: Re:VIEW BibLaTeX 拡張サンプル
language: ja
aut: ["Re:VIEW BibLaTeX sample"]
date: 2026-06-11

htmlext: html
stylesheet: ["style.css"]

texstyle: ["reviewmacro"]

biblatex:
  files:
    - references.bib
  style: review.csl
